version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./volumes:/app
  api:
    build: .
    restart: always
    environment:
      VIRTUAL_HOST: ${DOMAIN}
    networks:
      - proxy
    expose:
      - 3003
    ports:
      - '3003:3003'

networks:
  proxy:
    external: true